### ISSUE TITLE
在 centos 上使用 rbenv-china-mirror 插件出现以下错误

### ISSUE THREAD

**Issue by ywjno** [AndorChen/rbenv-china-mirror#5]
```bash
$ rbenv install 2.3.0
Downloading ruby-2.3.0.tar.bz2...
-> https://cache.ruby-china.org/pub/ruby/2.3/ruby-2.3.0.tar.bz2
error: failed to download ruby-2.3.0.tar.bz2

BUILD FAILED (CentOS 6.7 using ruby-build 20160330-14-g83348a8)
```

PS：在 Debian 下也出现这个问题

**Comment by AndorChen** [comment]
试试直接下载 https://cache.ruby-china.org/pub/ruby/2.3/ruby-2.3.0.tar.bz2 是否可以。

**Comment by ywjno** [comment]
用 wget 是可以直接下载回来的

**Comment by AndorChen** [comment]
没安装这个插件之前是正常的吗？

**Comment by ywjno** [comment]
没安装插件用 rbenv 按照是正常的

**Comment by AndorChen** [comment]
有没有挂 VPN 或者使用其他科学上网方式？

**Comment by ywjno** [comment]
并没有挂这种方式

**Comment by AndorChen** [comment]
网络正常，下载地址也正确。无解。（挠头

我再想想……

**Comment by ywjno** [comment]
等我多找几台机器试试

**Comment by AndorChen** [comment]
我目前查到的信息都与 curl 有关。你可以重新安装 curl，然后再试试。

**Comment by youkeshu** [comment]
ubuntu16.04出现同样的问题……

**Comment by fangxing204** [comment]
同样问题，ubuntu16
Downloading ruby-2.2.1.tar.bz2...
-> https://cache.ruby-china.org/pub/ruby/2.2/ruby-2.2.1.tar.bz2
error: failed to download ruby-2.2.1.tar.bz2

BUILD FAILED (Ubuntu 16.04 using ruby-build 20160330-14-g83348a8)

**Comment by fangxing204** [comment]
这是 [ruby build](https://github.com/rbenv/ruby-build/issues/799)的问题大家试试这个
RUBY_CONFIGURE_OPTS=--disable-install-doc rbenv install 2.2.2

**Comment by AndorChen** [comment]
@ywjno 试试 @fangxing204 所说的方法，看行不行

**Comment by youkeshu** [comment]
@AndorChen  错误依旧
RUBY_CONFIGURE_OPTS=--disable-install-doc rbenv install 2.3.0
Downloading ruby-2.3.0.tar.bz2...
-> https://cache.ruby-china.org/pub/ruby/2.3/ruby-2.3.0.tar.bz2
error: failed to download ruby-2.3.0.tar.bz2

BUILD FAILED (Ubuntu 16.04 using ruby-build 20160330-14-g83348a8)

我发现命令行下直接使用wget或者curl下载也是失败的，把下载地址复制到浏览器下载，要等3～5秒才出现开始下载，下载速度秒完成。
wget出错信息如下：
wget https://cache.ruby-china.org/pub/ruby/2.3/ruby-2.3.0.tar.bz2
--2016-04-25 13:19:32--  https://cache.ruby-china.org/pub/ruby/2.3/ruby-2.3.0.tar.bz2
正在解析主机 cache.ruby-china.org (cache.ruby-china.org)... 101.227.182.130, 120.132.136.18
正在连接 cache.ruby-china.org (cache.ruby-china.org)|101.227.182.130|:443... 已连接。
错误: 无法验证 cache.ruby-china.org 的由 “CN=StartCom Class 1 DV Server CA,OU=StartCom Certification Authority,O=StartCom Ltd.,C=IL” 颁发的证书:
  无法本地校验颁发者的权限。
要以不安全的方式连接至 cache.ruby-china.org，使用“--no-check-certificate”。

curl出错信息如下：
curl https://cache.ruby-china.org/pub/ruby/2.3/ruby-2.3.0.tar.bz2
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

**Comment by AndorChen** [comment]
@youkeshu 你的问题是没有 SSL 证书，根据你使用的系统，搜索一下添加方法。

@ywjno 根据 @youkeshu 的反馈，你也可以看看是不是 SSL 证书的问题。

**Comment by youkeshu** [comment]
添加证书后十分流畅的下载安装完成啦2.3.0,谢谢@AndorChen

**Comment by AndorChen** [comment]
无法下载的问题可能与服务器的配置有关，参见推文 https://twitter.com/huacnlee/status/725165517401550848

**Comment by ywjno** [comment]
看来是源的 SSL 配置的问题，晚上找个机器试试没问题我就关了
